### PR TITLE
add "heroku-16" as stack version

### PR DESCRIPTION
**Pull request by msuzukiheroku**
in order to run on Ruby 2.2.0.

### CODE REVIEW

**Comment by jonmountjoy** [comment]
Given that Heroku 18 is now the default step, I wonder if it shouldn't be set to that?   Or, given that it's not specified, I assume it defaults to Heroku 18 anyway?

**Comment by jonmountjoy** [comment]
Ah, the app doesn't work on heroku-18 👎  I'll fix that now.

**Comment by jonmountjoy** [comment]
I've updated the app dependencies so we no longer need the stack - so it should all work now.  Thanks for highlighting the problem.

**Comment by msuzukiheroku** [comment]
Thank you for fixing the issue :-)

2018年9月14日(金) 21:44 Jon Mountjoy <notifications@github.com>:

**Pull request closed without merging**
